### ISSUE TITLE
404 errors trying to load examples. 

### ISSUE THREAD

**Issue by jetdillo** [ihuicatl/jupyterlab-urdf#4]
I'm seeing lots of errors when trying to load the example URDFs:
```
[W 2022-07-07 23:29:41.496 ServerApp] 404 GET /ros/pkgs/spot_description/meshes/base.stl (127.0.0.1) 15.71ms referer=http://localhost:8888/lab/workspaces/auto-G/tree/examples/spot.urdf
[W 2022-07-07 23:29:41.498 ServerApp] 404 GET /ros/pkgs/spot_description/meshes/fr.lleg.stl (127.0.0.1) 1.09ms referer=http://localhost:8888/lab/workspaces/auto-G/tree/examples/spot.urdf
[W 2022-07-07 23:29:41.501 ServerApp] 404 GET /ros/pkgs/spot_description/meshes/fl.hip.stl (127.0.0.1) 2.34ms referer=http://localhost:8888/lab/workspaces/auto-G/tree/examples/spot.urdf
[W 2022-07-07 23:29:41.502 ServerApp] 404 GET /ros/pkgs/spot_description/meshes/fl.uleg.stl (127.0.0.1) 2.77ms referer=http://localhost:8888/lab/workspaces/auto-G/tree/examples/spot.urdf

This happens whether I source my ~/catkin_ws/devel/setup.bash script or not. 

I don't have any directories named /ros/pkgs, nor do there appear to be any in the repo. 

It would be helpful if there were some additional hints about startup, whether we should be setting any environment variables or passing additional arguments to jupyterlab-urdf from the command-line. 
Thanks!

**Comment by ihuicatl** [comment]
This should be resolved by installing `jupyterlab-ros` in your environment
```sh
conda install jupyterlab-ros -c robostack
```
I need to add this detail to the documentation, but let me know if that still doesn't work.

**Comment by jetdillo** [comment]
Cool. Thanks. I'll try that.
 I figured it had to be something like that because the Niryo model *mostly* loads and the [Tenacity Rover](https://github.com/jetdillo/tenacity_rover) URDF partially loads as well, but can't find all the meshes. 

I'll let you know what happens.

**Comment by jetdillo** [comment]
I have a new, fresh conda environment I'm running jupyterlab-ros in and still seeing these errors.
It looks like the Jupyter server is pre-pending some sort of path to the request:

`[W 2022-07-10 16:16:00.966 ServerApp] 404 GET /ros/pkgs/urdf_tutorial/meshes/l_finger.dae (127.0.0.1) 1.33ms referer=http://localhost:8888/lab/tree/jupyterlab-urdf/examples/niryo.urdf`

Because that file exists in the robostack repo:
```
(ros_env):~/miniconda3/envs/ros_env$ find . -name "l_finger.dae"
./pkgs/urdf_tutorial/meshes/l_finger.dae
./pkgs/ros-noetic-urdf-tutorial-0.5.0-py39h6fdeb60_13/share/urdf_tutorial/meshes/l_finger.dae
./share/urdf_tutorial/meshes/l_finger.dae
(ros_env):~/miniconda3/envs/ros_env
```
I tried setting the ROS_PACKAGE_PATH to include the `urdf_tutorial` package, but that didn't help. 
(The Foxglove-Studio app also has a bug with its ROS_PACKAGE_PATH expansion when trying to load URDFs) 

I'm not a total expert with Jupyter, so it's possible I'm missing something fundamental here.

**Comment by jetdillo** [comment]
I had a chance to get back to this and re-install from scratch and got it working.
The key steps I did in addition to the above was to 
- set up a proper catkin env inside the robostackenv
- source the $CATKIN_PATH/devel/setup.bash 
- from within the jupyterlab-urdf source, launch `jupyter lab` and click on the niryo.urdf or burger.urdf inside examples. 
- The key thing here is that jupyter reads the `$ROS_ROOT` set up by `setup.bash`. It's not a private Jupyter variable. If it's not set, even if everything inside the robostackenv seem to work from a shell command-line, 

This might be obvious to some, but not being overly familiar with jupyter, it took a bit for me to figure out.
